### ISSUE TITLE
A little information...

### ISSUE THREAD

**Issue by alexmercerind** [YAndoRak/botmessenger#6]
I wanted to give a bit of advice.

In scrapping.py on line 14, you don't need to encode the search term(s) yourself.
youtube-search-python can do it itself... But if you encode it yourself before passing, then it will be escaped two times and your search results may be incorrect.

>You should remove line
>```python
>escaped_search_term = search_term.replace(' ', '+')
>```
>and pass search_term directly.

I thought that I should provide you bit of assistance or help.
Close the issue!

Thankyou for using the module! 😀

**Comment by YAndoRak** [comment]
Hello ! 

We just fixed the problem, so thank you for your help and for creating the module which is very useful :smiley:
